apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: kirollos0/my-nginx:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
